SCD-63
olegsklyarov/self-control-diary pull request #84
Opened 2021-02-18 06:59 UTC by ZhdanovO

https://github.com/olegsklyarov/self-control-diary/issues/63

2021-02-18 07:31 UTC, olegsklyarov requested changes
👍 Все отлично, только исправить минорное замечание по форматированию (написал в комментарии к коду)

2021-02-18 07:31 UTC, olegsklyarov commented on http-request/mencho.http
> +Authorization: Bearer {{token}}
Добавить пустую строку в конце файла.

2021-02-18 07:44 UTC, olegsklyarov commented on tests/Api/ApiMenchoSamayaDeleteCest.php
> +        $mantraSamayaChenrezig = new MenchoSamaya($diary, $mantraChenrezig, 200);
`menchoSamayaChenrezig`

2021-02-18 09:25 UTC, ZhdanovO commented on http-request/mencho.http
> +Authorization: Bearer {{token}}
done

2021-02-18 09:25 UTC, ZhdanovO commented on tests/Api/ApiMenchoSamayaDeleteCest.php
> +        $mantraSamayaChenrezig = new MenchoSamaya($diary, $mantraChenrezig, 200);
done

2021-02-20 07:26 UTC, olegsklyarov approved these changes

2021-02-20 07:26 UTC, merged