SCD-64
olegsklyarov/self-control-diary pull request #88
Opened 2021-02-27 11:52 UTC by ZhdanovO

https://github.com/olegsklyarov/self-control-diary/issues/64

2021-02-27 11:54 UTC, ZhdanovO commented
@olegsklyarov привет!
Мне кажется я что то не то делаю. 
В тесте при неавторизованном пользователе у меня приходит 404, а не 401(

2021-02-28 14:43 UTC, olegsklyarov requested changes
Отписал замечания по коду

2021-02-28 14:43 UTC, olegsklyarov commented on src/Service/Mencho/MenchoSamayaService.php
> +        } catch (\Throwable $e) {
Тут отлавливаются все исключения, так что до контроллера ошибка не дойдёт. Нужно убрать try / catch, и довить исключения там, чтобы возвращать в ответе описание ошибки

2021-02-28 14:43 UTC, olegsklyarov commented on tests/Api/ApiMenchoSamayaDeleteByDiaryAndMantraUuidCest.php
> +        $I->seeResponseCodeIs(HttpCode::NOT_FOUND);
Добавить поверку message, который должен говорить, что Diary not found

2021-02-28 14:43 UTC, olegsklyarov commented on tests/Api/ApiMenchoSamayaDeleteByDiaryAndMantraUuidCest.php
> +        $I->seeResponseCodeIs(HttpCode::NOT_FOUND);
Проверить message

2021-03-09 05:07 UTC, closed without merging

2021-03-09 05:07 UTC, ZhdanovO commented
что то я с этим пулл реквестом не подружился. Сейчас попробую еще раз